# postgres
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./client
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  postgres_data:
