"""Initial Migration

Revision ID: 1b64d13e9530
Revises:
Create Date: 2025-04-09 12:53:51.062658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '1b64d13e9530'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('content_piece', sa.Column('embedding', Vector(dim=768), nullable=True))
    op.drop_index('ix_content_piece_content_trigram', table_name='content_piece', postgresql_using='gin')
    op.drop_index('ix_content_piece_content_tsv', table_name='content_piece', postgresql_using='gin')
    op.drop_index('ix_content_piece_title_trigram', table_name='content_piece', postgresql_using='gin')
    op.drop_index('ix_content_piece_title_tsv', table_name='content_piece', postgresql_using='gin')
    op.create_index('ix_content_piece_trigram', 'content_piece', [sa.text('title gin_trgm_ops'), sa.text('content gin_trgm_ops')], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_piece_trigram', table_name='content_piece', postgresql_using='gin')
    op.create_index('ix_content_piece_title_tsv', 'content_piece', ['title_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_content_piece_title_trigram', 'content_piece', ['title'], unique=False, postgresql_using='gin')
    op.create_index('ix_content_piece_content_tsv', 'content_piece', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_content_piece_content_trigram', 'content_piece', ['content'], unique=False, postgresql_using='gin')
    op.drop_column('content_piece', 'embedding')
    # ### end Alembic commands ###
